USE [ADT]
GO

/****** Object:  Index [RW_PK_Encounter_EncounterID]    Script Date: 10/18/2020 11:25:53 AM ******/
ALTER TABLE [dbo].[Encounter] ADD  CONSTRAINT [RW_PK_Encounter_EncounterID] PRIMARY KEY CLUSTERED 
(
	[EncounterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO


/****** Object:  Index [RW_PK_Arrival_ArrivalID]    Script Date: 10/18/2020 11:20:18 AM ******/
ALTER TABLE [dbo].[Arrival] ADD  CONSTRAINT [RW_PK_Arrival_ArrivalID] PRIMARY KEY NONCLUSTERED 
(
	[ArrivalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)

GO

/****** Object:  Index [RW_PK_EncounterLocation_EncounterLocationID]    Script Date: 10/18/2020 11:27:29 AM ******/
ALTER TABLE [dbo].[EncounterLocation] ADD  CONSTRAINT [RW_PK_EncounterLocation_EncounterLocationID] PRIMARY KEY NONCLUSTERED 
(
	[EncounterLocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)

GO

/****** Object:  Index [RW_PK_Departure_DepartureID]    Script Date: 10/18/2020 11:27:49 AM ******/
ALTER TABLE [dbo].[Departure] ADD  CONSTRAINT [RW_PK_Departure_DepartureID] PRIMARY KEY CLUSTERED 
(
	[DepartureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

