'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PackageSenderWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PackageSenderWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PackageSenderWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendOnePackageByHISKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSendStatusByHISKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSendStatusByEncounterIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.HIS_Tester.My.MySettings.Default.HIS_Tester_PackageSenderWebService_PackageSenderWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendOnePackageByHISKeyCompleted As SendOnePackageByHISKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSendStatusByHISKeyCompleted As GetSendStatusByHISKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSendStatusByEncounterIDCompleted As GetSendStatusByEncounterIDCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOnePackageByHISKey", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendOnePackageByHISKey(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal childServiceType As System.Nullable(Of eChildServiceType), ByRef errorMessage As String) As String
            Dim results() As Object = Me.Invoke("SendOnePackageByHISKey", New Object() {hisKey, serviceType, childServiceType, errorMessage})
            errorMessage = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendOnePackageByHISKeyAsync(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, ByVal childServiceType As System.Nullable(Of eChildServiceType), ByVal errorMessage As String)
            Me.SendOnePackageByHISKeyAsync(hisKey, serviceType, childServiceType, errorMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendOnePackageByHISKeyAsync(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, ByVal childServiceType As System.Nullable(Of eChildServiceType), ByVal errorMessage As String, ByVal userState As Object)
            If (Me.SendOnePackageByHISKeyOperationCompleted Is Nothing) Then
                Me.SendOnePackageByHISKeyOperationCompleted = AddressOf Me.OnSendOnePackageByHISKeyOperationCompleted
            End If
            Me.InvokeAsync("SendOnePackageByHISKey", New Object() {hisKey, serviceType, childServiceType, errorMessage}, Me.SendOnePackageByHISKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendOnePackageByHISKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendOnePackageByHISKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendOnePackageByHISKeyCompleted(Me, New SendOnePackageByHISKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSendStatusByHISKey", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSendStatusByHISKey(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal childServiceType As System.Nullable(Of eChildServiceType)) As SendStatusResult
            Dim results() As Object = Me.Invoke("GetSendStatusByHISKey", New Object() {hisKey, serviceType, childServiceType})
            Return CType(results(0),SendStatusResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSendStatusByHISKeyAsync(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, ByVal childServiceType As System.Nullable(Of eChildServiceType))
            Me.GetSendStatusByHISKeyAsync(hisKey, serviceType, childServiceType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSendStatusByHISKeyAsync(ByVal hisKey As SepasService_HIS_Key, ByVal serviceType As eServiceType, ByVal childServiceType As System.Nullable(Of eChildServiceType), ByVal userState As Object)
            If (Me.GetSendStatusByHISKeyOperationCompleted Is Nothing) Then
                Me.GetSendStatusByHISKeyOperationCompleted = AddressOf Me.OnGetSendStatusByHISKeyOperationCompleted
            End If
            Me.InvokeAsync("GetSendStatusByHISKey", New Object() {hisKey, serviceType, childServiceType}, Me.GetSendStatusByHISKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSendStatusByHISKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSendStatusByHISKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSendStatusByHISKeyCompleted(Me, New GetSendStatusByHISKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSendStatusByEncounterID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSendStatusByEncounterID(ByVal encounterId As Long, ByVal serviceType As eServiceType) As SendStatusResult()
            Dim results() As Object = Me.Invoke("GetSendStatusByEncounterID", New Object() {encounterId, serviceType})
            Return CType(results(0),SendStatusResult())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSendStatusByEncounterIDAsync(ByVal encounterId As Long, ByVal serviceType As eServiceType)
            Me.GetSendStatusByEncounterIDAsync(encounterId, serviceType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSendStatusByEncounterIDAsync(ByVal encounterId As Long, ByVal serviceType As eServiceType, ByVal userState As Object)
            If (Me.GetSendStatusByEncounterIDOperationCompleted Is Nothing) Then
                Me.GetSendStatusByEncounterIDOperationCompleted = AddressOf Me.OnGetSendStatusByEncounterIDOperationCompleted
            End If
            Me.InvokeAsync("GetSendStatusByEncounterID", New Object() {encounterId, serviceType}, Me.GetSendStatusByEncounterIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSendStatusByEncounterIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSendStatusByEncounterIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSendStatusByEncounterIDCompleted(Me, New GetSendStatusByEncounterIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SepasService_HIS_Key
        
        Private dispenser_KeyField As String
        
        Private billPatient_EncounterIdField As System.Nullable(Of Long)
        
        Private admitted_EncounterIdField As System.Nullable(Of Long)
        
        Private deathCertificate_EncounterIdField As System.Nullable(Of Long)
        
        Private referralFeedBack_EncounterIdField As System.Nullable(Of Long)
        
        Private referral_EncounterIdField As System.Nullable(Of Long)
        
        Private imagingPrescription_OrderDocIdField As System.Nullable(Of Long)
        
        Private prescriber_MedicationPrescriptionIdField As System.Nullable(Of Long)
        
        Private laboratory_ServiceOrderIdField As System.Nullable(Of Long)
        
        Private pathology_ServiceOrderIdField As System.Nullable(Of Long)
        
        Private laboratoryPrescription_LabSpecimenSpecsIdField As System.Nullable(Of Long)
        
        Private bed_EncounterLocationIdField As System.Nullable(Of Long)
        
        Private bed_DateOfField As Date
        
        Private bed_BedIdField As System.Nullable(Of Long)
        
        Private bed_BedStateField As eBedStatus
        
        '''<remarks/>
        Public Property Dispenser_Key() As String
            Get
                Return Me.dispenser_KeyField
            End Get
            Set
                Me.dispenser_KeyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BillPatient_EncounterId() As System.Nullable(Of Long)
            Get
                Return Me.billPatient_EncounterIdField
            End Get
            Set
                Me.billPatient_EncounterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Admitted_EncounterId() As System.Nullable(Of Long)
            Get
                Return Me.admitted_EncounterIdField
            End Get
            Set
                Me.admitted_EncounterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DeathCertificate_EncounterId() As System.Nullable(Of Long)
            Get
                Return Me.deathCertificate_EncounterIdField
            End Get
            Set
                Me.deathCertificate_EncounterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ReferralFeedBack_EncounterId() As System.Nullable(Of Long)
            Get
                Return Me.referralFeedBack_EncounterIdField
            End Get
            Set
                Me.referralFeedBack_EncounterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Referral_EncounterId() As System.Nullable(Of Long)
            Get
                Return Me.referral_EncounterIdField
            End Get
            Set
                Me.referral_EncounterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ImagingPrescription_OrderDocId() As System.Nullable(Of Long)
            Get
                Return Me.imagingPrescription_OrderDocIdField
            End Get
            Set
                Me.imagingPrescription_OrderDocIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Prescriber_MedicationPrescriptionId() As System.Nullable(Of Long)
            Get
                Return Me.prescriber_MedicationPrescriptionIdField
            End Get
            Set
                Me.prescriber_MedicationPrescriptionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Laboratory_ServiceOrderId() As System.Nullable(Of Long)
            Get
                Return Me.laboratory_ServiceOrderIdField
            End Get
            Set
                Me.laboratory_ServiceOrderIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Pathology_ServiceOrderId() As System.Nullable(Of Long)
            Get
                Return Me.pathology_ServiceOrderIdField
            End Get
            Set
                Me.pathology_ServiceOrderIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LaboratoryPrescription_LabSpecimenSpecsId() As System.Nullable(Of Long)
            Get
                Return Me.laboratoryPrescription_LabSpecimenSpecsIdField
            End Get
            Set
                Me.laboratoryPrescription_LabSpecimenSpecsIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Bed_EncounterLocationId() As System.Nullable(Of Long)
            Get
                Return Me.bed_EncounterLocationIdField
            End Get
            Set
                Me.bed_EncounterLocationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bed_DateOf() As Date
            Get
                Return Me.bed_DateOfField
            End Get
            Set
                Me.bed_DateOfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Bed_BedId() As System.Nullable(Of Long)
            Get
                Return Me.bed_BedIdField
            End Get
            Set
                Me.bed_BedIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bed_BedState() As eBedStatus
            Get
                Return Me.bed_BedStateField
            End Get
            Set
                Me.bed_BedStateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eBedStatus
        
        '''<remarks/>
        Full
        
        '''<remarks/>
        Empty
        
        '''<remarks/>
        Reserved
        
        '''<remarks/>
        Discharging
        
        '''<remarks/>
        OutOfService
        
        '''<remarks/>
        InTransition
        
        '''<remarks/>
        ReturnFromDischarging
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendStatusSuccessResult
        
        Private runSessionIdField As Long
        
        Private messageUIDField As String
        
        Private startDateField As Date
        
        Private endDateField As Date
        
        '''<remarks/>
        Public Property RunSessionId() As Long
            Get
                Return Me.runSessionIdField
            End Get
            Set
                Me.runSessionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageUID() As String
            Get
                Return Me.messageUIDField
            End Get
            Set
                Me.messageUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendStatusFailedResult
        
        Private runSessionIdField As Long
        
        Private messageUIDField As String
        
        Private startDateField As Date
        
        Private endDateField As System.Nullable(Of Date)
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property RunSessionId() As Long
            Get
                Return Me.runSessionIdField
            End Get
            Set
                Me.runSessionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageUID() As String
            Get
                Return Me.messageUIDField
            End Get
            Set
                Me.messageUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EndDate() As System.Nullable(Of Date)
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendStatusResult
        
        Private packageInfoIdField As Long
        
        Private mRNField As String
        
        Private failedListField() As SendStatusFailedResult
        
        Private successListField() As SendStatusSuccessResult
        
        '''<remarks/>
        Public Property PackageInfoId() As Long
            Get
                Return Me.packageInfoIdField
            End Get
            Set
                Me.packageInfoIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MRN() As String
            Get
                Return Me.mRNField
            End Get
            Set
                Me.mRNField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FailedList() As SendStatusFailedResult()
            Get
                Return Me.failedListField
            End Get
            Set
                Me.failedListField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuccessList() As SendStatusSuccessResult()
            Get
                Return Me.successListField
            End Get
            Set
                Me.successListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eServiceType
        
        '''<remarks/>
        BillPatient
        
        '''<remarks/>
        Admitted
        
        '''<remarks/>
        Bed
        
        '''<remarks/>
        Pathology
        
        '''<remarks/>
        DeathCertificate
        
        '''<remarks/>
        ReferralFeedBack
        
        '''<remarks/>
        Laboratory
        
        '''<remarks/>
        Prescriber
        
        '''<remarks/>
        Dispenser
        
        '''<remarks/>
        Referral
        
        '''<remarks/>
        ImagingPrescription
        
        '''<remarks/>
        LaboratoryPrescription
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eChildServiceType
        
        '''<remarks/>
        BillPatient_InPatient
        
        '''<remarks/>
        BillPatient_OutPatient
        
        '''<remarks/>
        BillPatient_Emergency
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendOnePackageByHISKeyCompletedEventHandler(ByVal sender As Object, ByVal e As SendOnePackageByHISKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendOnePackageByHISKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property errorMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSendStatusByHISKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetSendStatusByHISKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSendStatusByHISKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SendStatusResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SendStatusResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSendStatusByEncounterIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetSendStatusByEncounterIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSendStatusByEncounterIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SendStatusResult()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SendStatusResult())
            End Get
        End Property
    End Class
End Namespace
